"""Synthetic-SVD cross-fit (ceiling test) — self-contained experimental package.

Fit the SVD base scorer on SYNTHETIC trajectories (generated by ``datagen/``) and
benchmark it against in-distribution fitting on the IDENTICAL 325 test splits that feed
``outputs/<ds>/tables/325/results_extended.tsv``. This is a ceiling probe (the
gaia+assistantbench fit pool leaks into the real test sets), kept apart from the core
``src/`` pipeline: everything new lives here and only IMPORTS the core primitives —
``src/score/svd.py`` (fit/score decoupling), ``src/rescore/`` (CRR + backprop),
``src/reports/reduce.py`` (reductions) and ``src/reports/main_table.py`` (table layout)
— never modifying them.

Stages (see ``run.py``): extract -> score -> rescore -> table.
"""
