"""Every stage's root path, derived from a resolved config.

ONE place computes the whole tree so no stage ever hand-writes a path. Two rules:

  * **Raw data is input, not output.** Trajectory JSONs live in ``data/<ds>/`` —
    they are the corpus, versioned alongside the code, never regenerated by a run.
  * **Everything a run produces lives under ``outputs/<ds>/``**, including the
    extracted representations/attention (they ARE stage outputs — of the extract
    stage — even though every later stage consumes them as input).

Split-tagging: stages whose results depend on the train/val/test partition are
nested under a split tag (``0.3/0.2/0.5 -> "325"``) so alternative partitions never
collide. Extraction is split-independent, so it is NOT tagged — which is exactly why
overriding ``split_tag`` re-runs the cheap analysis stages while reusing the
expensive forward passes.

Layout::

    data/<ds>/<subset>/*.json                                    data_root   (corpus)
    outputs/<ds>/activations/<model>/<subset>/*.safetensors      reps_root   (untagged)
    outputs/<ds>/attention/<model>/<subset>/*.safetensors        attn_root   (untagged)
    outputs/<ds>/scores/<tag>/<model>/<subset>/seed-<n>.tsv      scores_root
    outputs/<ds>/rescore/<tag>/<model>/<subset>/sweep.tsv        rescore_root
    outputs/<ds>/reduced/<tag>/<model>/<subset>/*.tsv            reduced_root
    outputs/<ds>/tables/<tag>/*.tsv                              tables_root
    outputs/<ds>/analysis/<tag>/geometry/<model>/<subset>/*.tsv  analysis_root
    outputs/<ds>/reproductions/<tag>/<model>/<subset>/*          repro_root
    outputs/<ds>/<stage>/runs/<stage>-<utc>.json                 provenance

``outputs_base`` / ``data_base`` can be overridden in a manifest to point at a
scratch or shared location without touching any stage code.
"""
from __future__ import annotations

from pathlib import Path

from .config import split_tag


def _ds(cfg: dict) -> str:
    """Dataset name: ``dataset`` on thin stage configs, ``name`` on a manifest."""
    return cfg.get("dataset") or cfg.get("name")


def outputs_base(cfg: dict) -> Path:
    return Path(cfg.get("outputs_base") or f"outputs/{_ds(cfg)}")


def tag(cfg: dict) -> str:
    return split_tag(cfg["splits"], cfg.get("split_tag"))


# ── corpus (never written by a run) ─────────────────────────────────────────
def data_root(cfg: dict) -> Path:
    return Path(cfg.get("data_base") or "data") / _ds(cfg)


# ── extraction outputs (split-independent -> not tagged) ────────────────────
def reps_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "activations"


def attn_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "attention"


# ── derived, split-tagged stage roots ───────────────────────────────────────
def scores_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "scores" / tag(cfg)


def rescore_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "rescore" / tag(cfg)


def reduced_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "reduced" / tag(cfg)


def tables_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "tables" / tag(cfg)


def analysis_root(cfg: dict) -> Path:
    return outputs_base(cfg) / "analysis" / tag(cfg)


def repro_root(cfg: dict) -> Path:
    """Per-step reproductions of a single frozen config (for inspection / plotting)."""
    return outputs_base(cfg) / "reproductions" / tag(cfg)


def runs_dir(cfg: dict, stage: str) -> Path:
    """Per-stage provenance directory: ``outputs/<ds>/<stage>/runs/``."""
    return outputs_base(cfg) / stage / "runs"
